-- Google Gemini TTS ボイスの seed データ

INSERT INTO voices (provider, provider_voice_id, name, gender, sample_audio_url) VALUES
	('google', 'Achernar', 'Achernar', 'female', '/voice/sample.wav'),
	('google', 'Achird', 'Achird', 'male', '/voice/sample.wav'),
	('google', 'Algenib', 'Algenib', 'male', '/voice/sample.wav'),
	('google', 'Algieba', 'Algieba', 'male', '/voice/sample.wav'),
	('google', 'Alnilam', 'Alnilam', 'male', '/voice/sample.wav'),
	('google', 'Aoede', 'Aoede', 'female', '/voice/sample.wav'),
	('google', 'Autonoe', 'Autonoe', 'female', '/voice/sample.wav'),
	('google', 'Callirrhoe', 'Callirrhoe', 'female', '/voice/sample.wav'),
	('google', 'Charon', 'Charon', 'male', '/voice/sample.wav'),
	('google', 'Despina', 'Despina', 'female', '/voice/sample.wav'),
	('google', 'Enceladus', 'Enceladus', 'male', '/voice/sample.wav'),
	('google', 'Erinome', 'Erinome', 'female', '/voice/sample.wav'),
	('google', 'Fenrir', 'Fenrir', 'male', '/voice/sample.wav'),
	('google', 'Gacrux', 'Gacrux', 'female', '/voice/sample.wav'),
	('google', 'Iapetus', 'Iapetus', 'male', '/voice/sample.wav'),
	('google', 'Kore', 'Kore', 'female', '/voice/sample.wav'),
	('google', 'Laomedeia', 'Laomedeia', 'female', '/voice/sample.wav'),
	('google', 'Leda', 'Leda', 'female', '/voice/sample.wav'),
	('google', 'Orus', 'Orus', 'male', '/voice/sample.wav'),
	('google', 'Puck', 'Puck', 'male', '/voice/sample.wav'),
	('google', 'Pulcherrima', 'Pulcherrima', 'female', '/voice/sample.wav'),
	('google', 'Rasalgethi', 'Rasalgethi', 'male', '/voice/sample.wav'),
	('google', 'Sadachbia', 'Sadachbia', 'male', '/voice/sample.wav'),
	('google', 'Sadaltager', 'Sadaltager', 'male', '/voice/sample.wav'),
	('google', 'Schedar', 'Schedar', 'male', '/voice/sample.wav'),
	('google', 'Sulafat', 'Sulafat', 'female', '/voice/sample.wav'),
	('google', 'Umbriel', 'Umbriel', 'male', '/voice/sample.wav'),
	('google', 'Vindemiatrix', 'Vindemiatrix', 'female', '/voice/sample.wav'),
	('google', 'Zephyr', 'Zephyr', 'female', '/voice/sample.wav'),
	('google', 'Zubenelgenubi', 'Zubenelgenubi', 'male', '/voice/sample.wav');
