@baseUrl = http://localhost:8081/api/v1

# トークン生成: make token
@token = YOUR_TOKEN_HERE

### 画像アップロード
POST {{baseUrl}}/images
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

< ./test.png
--boundary--
