@baseUrl = http://localhost:8081/api/v1

### ボイス一覧取得
GET {{baseUrl}}/voices

### ボイス一覧取得（プロバイダでフィルタ）
GET {{baseUrl}}/voices?provider=google

### ボイス一覧取得（性別でフィルタ）
GET {{baseUrl}}/voices?gender=male

### ボイス一覧取得（複合フィルタ）
GET {{baseUrl}}/voices?provider=google&gender=female

### ボイス取得
@voiceId = 52cbccc4-46d7-4424-8a37-da36ee2951d1
GET {{baseUrl}}/voices/{{voiceId}}
